# Generated by Django 4.2 on 2023-04-22 16:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dimensiones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='nombre_categoria',
            field=models.CharField(default=django.utils.timezone.now, max_length=45, verbose_name='Categoria'),
            preserve_default=False,
        ),
    ]
